# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend
    exclude:
      - studio

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: "Build"
    jobs:
      - job: build
        displayName: "Build"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"

          - script: |
              yarn --frozen-lockfile
              yarn build
            displayName: "yarn install and build"
            workingDirectory: "frontend"

          - script: |
              cp -R public .next/standalone/public
              cp -R .next/static .next/standalone/.next/static
            displayName: "Copy public and static build files"
            workingDirectory: "frontend"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(Build.BinariesDirectory)/frontend/.next/standalone"
              includeRootFolder: true
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: deploy
    dependsOn: [build]
    displayName: "Deploy"
    jobs:
      - job: deploy
        displayName: "Deploy"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "current"
              artifactName: "drop"
              targetPath: "$(System.DefaultWorkingDirectory)"

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "Enterprise Dev/Test(a7d32964-b533-4f5e-a80d-66bf28040079)"
              appType: "webAppLinux"
              WebAppName: "svein-next-test"
              packageForLinux: "$(System.DefaultWorkingDirectory)/**/*.zip"
