# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend
    exclude:
      - studio

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: "Build"
    jobs:
      - job: build
        displayName: "Build"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"

          - script: |
              yarn --frozen-lockfile
              yarn build
            displayName: "yarn install and build"
            workingDirectory: "frontend"
            env:
              NEXT_PUBLIC_SANITY_PROJECT_ID: jhhsx3kh

          - script: |
              cp -R public .next/standalone/public
              cp -R .next/static .next/standalone/.next/static
            displayName: "Copy public and static build files"
            workingDirectory: "frontend"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/frontend/.next/standalone"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: deploy
    dependsOn: [build]
    displayName: "Deploy"
    jobs:
      - job: deploy
        displayName: "Deploy"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "current"
              artifactName: "drop"
              targetPath: "$(System.DefaultWorkingDirectory)"

          - task: AzureWebApp@1
            displayName: "Azure Web App Deploy: svein-next-test"
            inputs:
              azureSubscription: "59251117-66e1-470c-b684-b653f9f76665"
              appType: webAppLinux
              appName: "svein-next-test"
              runtimeStack: "NODE|14-lts"
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: "npm run start"
