# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend
    exclude:
      - studio

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "5a13c401-4f5b-4391-8bac-c6f09594cf22"

  # Web app name
  webAppName: "svein-next-test"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - script: |
              yarn --frozen-lockfile
              yarn build
            displayName: "yarn install and build"
            workingDirectory: "frontend"
            env:
              NEXT_PUBLIC_SANITY_PROJECT_ID: jhhsx3kh

          - script: |
              cp -R public .next/standalone/public
              cp -R .next/static .next/standalone/.next/static
            displayName: "Copy public and static build files"
            workingDirectory: "frontend"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/frontend/.next/standalone"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: $(vmImageName)
        steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: "Azure Web App Deploy: svein-next-test"
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: "NODE|16-lts"
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: "node server.js"
